"""PodLog

Revision ID: 8b04ab8f89f9
Revises: 
Create Date: 2025-05-07 17:50:05.144051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8b04ab8f89f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podlog',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('container_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('container_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('podlog')
    # ### end Alembic commands ###
