"""Add executors table

Revision ID: 0653dc97382a
Revises: d5037a3f7b99
Create Date: 2024-09-10 09:42:38.878136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0653dc97382a'
down_revision: Union[str, None] = 'd5037a3f7b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executor',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('miner_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('miner_port', sa.Integer(), nullable=False),
    sa.Column('miner_hotkey', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executor_id', sa.Uuid(), nullable=False),
    sa.Column('executor_ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executor_ssh_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executor_ssh_port', sa.Integer(), nullable=False),
    sa.Column('rented', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.add_column('task', sa.Column('executor_id', sa.Uuid(), nullable=False))
    op.drop_column('task', 'ssh_private_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('ssh_private_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('task', 'executor_id')
    op.drop_table('executor')
    # ### end Alembic commands ###
