FROM docker:26-cli
WORKDIR /root/validator
COPY docker-compose.app.dev.yml docker-compose.dev.yml
COPY entrypoint.sh /entrypoint.sh
COPY version.txt .

RUN chmod u+x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
