FROM docker:26-cli
WORKDIR /root/validator
COPY docker-compose.app.yml docker-compose.yml
COPY entrypoint.sh /entrypoint.sh

LABEL version="3.3.13"

RUN chmod u+x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
