services:
  db:
    image: postgres:14.0-alpine
    healthcheck:
      test: pg_isready -U postgres || exit 1
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    image: daturaai/redis:7.4.2
    environment:
      - REDIS_MODE=master
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: redis-cli ping
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  db_data:
  redis_data: