services:
  executor:
    image: daturaai/compute-subnet-executor:dev
    env_file: ./.env
    restart: always
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
      - ${SSH_PORT}:22
    expose:
      - ${INTERNAL_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker/daemon.json:/etc/docker/daemon.json
      - /etc/nvidia-container-runtime/config.toml:/etc/nvidia-container-runtime/config.toml
    pid: host
    healthcheck:
      test: ["CMD-SHELL", "nvidia-smi || exit 1"]
      interval: 2m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
