FROM docker:26-cli
WORKDIR /root/executor

COPY docker-compose.app.yml docker-compose.yml
COPY entrypoint.sh /entrypoint.sh
COPY version.txt .

RUN chmod u+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
