FROM docker:26-cli
WORKDIR /root/executor

COPY docker-compose.app.yml docker-compose.yml
COPY entrypoint.sh /entrypoint.sh

RUN chmod u+x /entrypoint.sh

LABEL version="3.3.1"

ENTRYPOINT ["/entrypoint.sh"]
