FROM docker:26-cli
WORKDIR /root/executor

ARG targetFile
COPY ${targetFile} docker-compose.yml
COPY entrypoint.sh /entrypoint.sh
COPY version.txt .

RUN chmod u+x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
