services:
  db:
    image: postgres:14.0-alpine
    healthcheck:
      test: pg_isready -U postgres || exit 1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=compute-subnet-db
    ports:
      - 8432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  executor:
    image: daturaai/compute-subnet-executor:dev
    env_file: ./.env
    restart: always
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
      - ${SSH_PORT}:22
    expose:
      - ${INTERNAL_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/docker/daemon.json:/etc/docker/daemon.json
      - /etc/nvidia-container-runtime/config.toml:/etc/nvidia-container-runtime/config.toml
    pid: host
    environment:
      - DB_URI=postgresql://postgres:password@db:5432/compute-subnet-db
    depends_on:
      - db
    labels:
      autoheal-app: true
    healthcheck:
      test: [ "CMD-SHELL", "nvidia-smi || exit 1" ]
      interval: 2m
      timeout: 10s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  monitor:
    image: daturaai/compute-subnet-executor:latest
    env_file: ./.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/kmsg:/dev/kmsg:ro
    pid: host
    command: python src/monitor.py
    environment:
      - DB_URI=postgresql://postgres:password@db:5432/compute-subnet-db
    depends_on:
      - executor
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
