"""create validator model

Revision ID: 8e52603bd563
Revises:
Create Date: 2024-07-15 10:47:41.596221

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e52603bd563"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "validator",
        sa.Column('uuid', sa.Uuid(), nullable=False),
        sa.Column('validator_hotkey', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('uuid'),
        sa.UniqueConstraint('validator_hotkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("validator")
    # ### end Alembic commands ###
