FROM docker:26-cli
WORKDIR /root/miner
COPY docker-compose.app.yml docker-compose.yml
COPY entrypoint.sh /entrypoint.sh

LABEL version="3.3.2"

RUN chmod u+x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
