FROM docker:26-cli
WORKDIR /root/miner
ARG targetFile
COPY ${targetFile} docker-compose.yml
COPY entrypoint.sh /entrypoint.sh
COPY version.txt .

RUN chmod u+x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
