name: "CD: Deploying Validator (dev) with Manual Trigger"

on:
  push:
    branches:
      - 'dev_validator'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TAG: "dev" 
      TARGET_FILE: "docker-compose.app.dev.yml"
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }} 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x neurons/validators/docker_publish.sh
          chmod +x neurons/validators/docker_runner_publish.sh
          
      - name: Run docker_publish.sh
        run: |
          cd neurons/validators
          ./docker_publish.sh
          
      - name: Run docker_runner_publish.sh
        run: |
          cd neurons/validators
          ./docker_runner_publish.sh
