name: "CD: validator (dev)"

on:
  push:
    branches:
      - 'dev_validator'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TAG: "dev" 
      DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }} 
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x neurons/validators/docker_publish.sh
          chmod +x neurons/validators/docker_runner_publish_dev.sh
          
      - name: Run docker_publish.sh
        run: |
          cd neurons/validators
          ./docker_publish.sh
          
      - name: Run docker_runner_publish_dev.sh
        run: |
          cd neurons/validators
          ./docker_runner_publish_dev.sh
